---

- name: load | Define OS and OS release
  set_fact:
    os_vars: 'Debian.yml'
    os_release_vars: 'Debian-{{ apt_distribution_major_version }}.yml'

- name: load | Show OS vars filenames
  debug:
    msg: "{{ role_path }}/vars/{{ os_vars }} , {{os_release_vars}}, {{ apt_suite }}"

- name: load | OS variables
  include_vars: "{{ os_vars }}"

- name: load | OS-specific variables
  include_vars: "{{ os_release_vars }}"

- name: load1
  include_vars:
    file: 'Debian.yml'
    name: d0

- name: load2
  include_vars:
    file: "{{ 'Debian-' + item + '.yml' }}"
    name: "{{ 'd_' + item }}"
  loop: ['6', '7', '8', '9', '10']

- name:
  set_fact:
    d_huys: >-
      {{ d_huys | combine({ item : vars['d_' + item] }) }}
  loop: ['6', '7', '8', '9', '10']

- name: debug
  debug:
    var: d_huys

- name: build1
  set_fact:
    apt_defaults: >-
      {{ apt_defaults
            | combine({ _item_name : d0 | combine(_item_d)})
      }}
  vars:
    _apt_suite: item.0
    _apt_ver: item.1
    _item_name: "{{ 'debian-' + item.1 | string }}"
    _item_d : >-
      {{ vars['d_' + item.1 | string] }}
  loop: "{{ [('squeeze', 6), ('wheezy', 7)] }}"

- name: debug
  debug:
    var: apt_defaults

