---

- name: load | Define OS and OS release
  set_fact:
    os_vars: 'Debian.yml'
    os_release_vars: 'Debian-{{ apt_distribution_major_version }}.yml'

- name: load | Show OS vars filenames
  debug:
    msg: "{{ role_path }}/vars/{{ os_vars }} , {{os_release_vars}}"

- name: load | OS variables
  include_vars: "{{ os_vars }}"

- name: load | OS-specific variables
  include_vars: "{{ os_release_vars }}"

