---

- block:
    - name: Define apt repositories list
      set_fact:
        _apt_repositories: >-
          {{ _apt_repositories
              + [ def_item | combine(item) ]
              + ( [ def_item_src | combine(item) ]
                    if item.add_src | default(apt_add_src)
                    else [] )
          }}
      vars:
        def_item: >-
          {{  { 'type'        : 'deb'
              , 'url'         : apt_default_mirror
              , 'dist'        : apt_suite
              , 'components'  : apt_components
              , 'trusted'     : false
              }
          }}
        def_item_src: >-
          {{ def_item | combine({'type': 'deb-src'}) }}
      loop: "{{ apt_repositories }}"

    - name: Extract apt repository preferences
      set_fact:
        _apt_repositories_prefs: >-
          {{  _apt_repositories_prefs
                + [ item | combine(
                      { 'pkgs'    : '*'
                      , 'comment' : "Generated for '" + item.dist + "'"
                                      + " from source '" + item.url + "'"
                      })
                  ]
          }}
      loop: >-
        {{ _apt_repositories
              | selectattr('type', 'equalto', 'deb')
              | selectattr('pin', 'defined')
              | list
        }}

    - name: Define apt preferences list
      set_fact:
        _apt_preferences: >-
          {{ _apt_preferences
              + [ def_item | combine(item) ]
          }}
      vars:
        # If underscore should be treated as word delimiter in 'n=' value, use
        # '([a-zA-Z0-9]+[-_])*' regex instead of '(\w+\W)*' below.
        def_item: >-
          {{  { 'pkgs'  : '*'
              , 'pin_priority' :
                  600 if item.pin
                          | regex_search(' n=(\w+\W)*' + apt_suite + '(\W\w+)*(, |$)') is not none
                    else 100
              }
          }}
      loop: "{{ apt_preferences + _apt_repositories_prefs }}"

    - name: Show apt repositories
      debug:
        var: _apt_repositories
    - name: Show apt preferences
      debug:
        var: _apt_preferences

- block:
    - name: Install sources.list
      template:
        src:    'sources.list'
        dest:   '/etc/apt/sources.list'
        force:  true
        backup: true
        owner:  'root'
        group:  'root'
        mode:   0644

    - name: Disabled Release file valid check
      template:
        src:    '99ignore-valid'
        dest:   '/etc/apt/apt.conf.d/99ignore-valid'
        force:  true
        backup: true
        owner:  'root'
        group:  'root'
        mode:   0644
        owner:  'root'
      when: apt_ignore_valid

    - name: Install apt preferences
      template:
        src:    'preferences'
        dest:   '/etc/apt/preferences'
        force:  true
        backup: true
        owner:  'root'
        group:  'root'
        mode:   0644

- block:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install archive keyring package
      package:
        name: >-
          {{ _apt_repositories 
                | selectattr('keyring', 'defined')
                | map(attribute='keyring')
                | list | default([])
          }}
        state: present
        allow_unauthenticated: true

