---

- name: Load OS variables
  import_tasks: load.yml
  tags:
    - always

- name: Define variables
  import_tasks: define.yml
  tags:
    - always

- block:
    - name: Install sources.list
      template:
        src:    'sources.list'
        dest:   "{{ sources_list }}"
        force:  true
        backup: true
        owner:  'root'
        group:  'root'
        mode:   0644
      register: sources_list_updated

    - name: Disabled Release file valid check
      template:
        src:    '99ignore-valid'
        dest:   '/etc/apt/apt.conf.d/99ignore-valid'
        force:  true
        backup: true
        owner:  'root'
        group:  'root'
        mode:   0644
      when: apt_ignore_valid

    - name: Install apt preferences
      template:
        src:    'preferences'
        dest:   "{{ preferences_pref }}"
        force:  true
        backup: true
        owner:  'root'
        group:  'root'
        mode:   0644

- block:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: sources_list_updated.changed

    - name: Install archive keyring package
      package:
        name: >-
          {{ _apt_repositories 
                | selectattr('keyring', 'defined')
                | map(attribute='keyring')
                | list | default([])
          }}
        state: present
        allow_unauthenticated: true

